server:
  shutdown: graceful
  port: 8085
spring:
  application:
    name: mongodb-reactive
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://mongo-primary:27017,mongo-replica:27018/bulk_demo?replicaSet=rs0&readPreference=primary&maxPoolSize=4&tls=false
  lifecycle:
    timeout-per-shutdown-phase: 5s

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
